[Honeypot Bot Trap Triggered]
action.list = 1
action.list.severity = 5
action.webhook.enable_allowlist = 0
alert.digest_mode = false
alert.severity = 5
alert.suppress = true
alert.suppress.fields = ip
alert.suppress.period = 300s
alert.track = true
counttype = number of events
cron_schedule = */5 * * * *
description = Tracks malicious automated scripts populating hidden web form elements
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.type = statistics
display.page.search.tab = statistics
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index="main" source="/opt/splunk/s3_data/*" "Bot filled hidden field" | iplocation ip | table _time ip City Country
